# Application Properties
app.name = PTVN-SOURCING-REQUEST-SERVICE

# Server
server.port= 8084
server.max-http-header-size=${MAX_HTTP_HEADER_SIZE}

caching.spring.userTimeZoneTTL=300000

# JPA settings
spring.jpa.show-sql = false
spring.jpa.hibernate.dialect = org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto = none
spring.jpa.properties.hibernate.format_sql = false
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.type=trace
spring.jpa.properties.hibernate.jdbc.batch_size = 20
spring.jpa.properties.hibernate.order_inserts = true
spring.jpa.properties.hibernate.order_updates = true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data = true
spring.jpa.properties.hibernate.proc.param_null_passing=true
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# Logging
logging.level.root=INFO
logging.level.org.springframework.boot.autoconfigure=ERROR
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql=trace

#Swagger
spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER
springdoc.swagger-ui.path=/api/sourcingreq/swagger-ui.html

# Version Api
api.endpoint.version=${API_ENDPOINT_VERSION}
jwt.header=Authorization
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.route.authentication.path=/oauth/token
jwt.route.authentication.refresh=/refreshToken

# File max size
spring.servlet.multipart.max-file-size=${FILE_MAX_SIZE}
spring.servlet.multipart.max-request-size=${FILE_MAX_REQUEST_SIZE}

# Localization i18n
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8

## Configuring info endpoint
info.app.name=Sourcing Request Services
info.app.description=Sourcing Request REST Api Services
info.app.version=1.0.0

spring.main.allow-circular-references=true

# Tomcat AJP
tomcat.ajp.port=9094
tomcat.ajp.remoteauthentication=false
tomcat.ajp.enabled=true

# SourcingRequest Datasource
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.jdbc-url=jdbc:sqlserver://${DATABASE_SOURCINGREQ_HOST_IP};databaseName=${DATABASE_SOURCINGREQ_NAME}
spring.datasource.username=${DATABASE_SOURCINGREQ_USERNAME}
spring.datasource.password=${DATABASE_SOURCINGREQ_PASSWORD}

# HEALTH ENDPOINT
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=info
management.info.git.mode=full

# Minio Configuration
minio.url=${MINIO_SERVER_URL}
minio.bucket=sourcing.request.service
minio.accessKey=AXz5nc7dUjHOWo0Ep9s0C
minio.secretKey=9t4PWh4bifICeWPSXl5
minio.folder=storage

#Basic auth for some api
basic.auth.username=${BASIC_AUTH_USERNAME}
basic.auth.password=${BASIC_AUTH_PASSWORD}

# EPAuth
epauth.auth.basic.username=${EPAUTH_AUTH_BASIC_USERNAME}
epauth.auth.basic.password=${EPAUTH_AUTH_BASIC_PASSWORD}

# UAA
uaa.auth.basic.username=${UAA_AUTH_BASIC_USERNAME}
uaa.auth.basic.password=${UAA_AUTH_BASIC_PASSWORD}
uaa.service.host=${UAA_SERVICE_HOST}

# BASE URL
base.url.api.uaa-bff= ${BASEURL_API_UAA_BFF}
base.url.api.workflow=${BASEURL_API_WORKFLOW}
base.url.api.epauth=${BASEURL_API_EPAUTH}
base.url.ptvn.cookie=${BASEURL_PTVN_COOKIE}
base.url.ptvn.supplier.webworks=${BASEURL_PTVN_SUPPLIER_WEBWORKS}
base.url.api.eform=${BASEURL_API_EFORM}
base.url.api.admin=${BASEURL_API_ADMIN}
base.url.api.delegate=${BASEURL_API_DELEGATE}
base.url.api.supplier.directory=${BASEURL_API_SUPPLIER_DIRECTORY}

# Workflow
workflow.auth.basic.username=${WORKFLOW_AUTH_BASIC_USERNAME}
workflow.auth.basic.password=${WORKFLOW_AUTH_BASIC_PASSWORD}


##--------------Authentication------------------
authentication.oneplanet.url=${AUTHENTICATION_ONEPLANET}
authentication.ep.url=${AUTHENTICATION_EP}

##--------------Third Party------------------
third.party.authentication.ep.url=${THIRD_PARTY_AUTHENTICATION_EP}

##------------------eRFX---------------------------
erfx.service.host=${ERFX_SERVICE_HOST}

##------------------AIT---------------------------
bifrost.service.host=${BIFROST_SERVICE_HOST}
bifrost.service.username=sourcingreq
bifrost.service.password=P@ssw0rd


##------------------Email---------------------------
email.service.host=${EMAIL_SERVICE_HOST}

##--------------SupplierWebWorks------------------
supplierWebWorks.x.ptvn.bypasstoken=${SUPPLIER_WEBWORKS_BYPASS_TOKEN}
supplierWebWorks.x.ptvn.service=AIT
#supplierWebWorks.invitationCode=AIT


##------------------OTHERS---------------------------
supplier.notify.email.template.id=${SUPPLIER_NOTIFY_EMAIL_TEMPLATE_ID}
supplier.notify.email.logo.url=${SUPPLIER_NOTIFY_EMAIL_LOGO_URL}

##--------------PTVN Admin------------------
ptvn-admin.x.ptvn.bypasstoken=${PTVN_ADMIN_BYPASS_TOKEN}

# Elasticsearch Configuration
elasticsearch.scheme=${ELASTIC_SCHEMAS}
elasticsearch.host=${ELASTIC_HOST}
elasticsearch.port=${ELASTIC_PORT}
management.health.elasticsearch.enabled=false

