package com.pantavanij.sourcingreq.services.enums;

public enum Activity {
    ACTIVITY_UNKNOWN(-1),
    ACTIVITY_SAVE(1),
    ACTIVITY_SUBMIT(2),
    ACTIVITY_DUPLICATE(3),
    ACTIVITY_CANCEL(4),
    ACTIVITY_CONFIRM(5),
    ACTIVITY_REJECT(6),
    ACTIVITY_ASSIGN(7),
    ACTIVITY_REMOVE(8),
    ACTIVITY_FORWARD(9),
    ACTIVITY_COPY_TO_PR(10),
    ACTIVITY_REVIEW_COMMENT(11),
    ACTIVITY_REVIEW_EDIT(12),
    ACTIVITY_EDIT(13),
    ACTIVITY_APPROVED(14), // RESERVED FOR DEPT APPROVER
    ACTIVITY_REJECTED(15), // RESERVED FOR DEPT APPROVER
    PDPA_NO_ATTACH(16),
    PDPA_IS_ATTACH(17),
    ACTIVITY_EXC_SOURCING_SUBMIT(18),
    ACTIVITY_EXC_SOURCING_APPROVED(19),
    ACTIVITY_EXC_SOURCING_REJECTED(20),
    ACTIVITY_COPY_TO_PR_FAILED(21),
    ACTIVITY_HISTORY(22),
    ACTIVITY_DELETE(23),
    ACTIVITY_CONVERT_ERFX(24),
    ACTIVITY_EXPORT_REPORT(25),
    ACTIVITY_QUESTIONNAIRE(26),
    ACTIVITY_SHEDLOCK(27)
    ;

    private final Integer id;

    Activity(Integer id) {
        this.id = id;
    }

    public Integer id() {
        return this.id;
    }
}
