package com.pantavanij.sourcingreq.services.enums;

public enum EmailActivity {
//    REQUESTER_SUBMIT_REQUEST(1),
//    PURCHASER_COMPLETE_REQUEST(2),
//    PURCHASER_LAST_COMPLETE_REQUEST(3),
//    PURCHASER_REJECT_REQUEST(4),
//    REQUESTER_CANCELLED_REQUEST(5),
    PLEASE_REVIEW_AND_APPROVE_SR(6),
    PLEASE_REVIEW_SR(7),
    SR_HAS_BEEN_REJECTED(8),
    SR_HAS_BEEN_CANCELLED(9),
    SR_HAS_BEEN_APPROVED(10),
    SR_HAS_BEEN_FORWARDED_FOR_PURCHASER_WHO_FORWARD_REQUEST_REQUESTER(11),
    SR_HAS_BEEN_FORWARDED_FOR_PURCHASER_WHO_RECEIVED_FORWARDED_REQUEST(12),
    DELEGATION_HAS_BEEN_CREATED_FOR_WHO_DELEGATE(13),
    DELEGATION_HAS_BEEN_CREATED_FOR_WHO_RECEIVED_DELEGATE(14),
    DELEGATION_HAS_BEEN_CANCELLED(15),
    SUPPLIER_NOTIFY(16),
    EXC_SR_IS_WAITING_FOR_PURCHASING_APPROVER_TO_APPROVE(17),
    EXC_SR_HAS_BEEN_APPROVED_BY_DEPT_APPROVER(18),
    EXC_SR_HAS_BEEN_REJECTED_BY_DEPT_APPROVER(19),
    EXC_SR_HAS_BEEN_APPROVED_BY_PURCHASING_APPROVER(20),
    EXC_SR_HAS_BEEN_REJECTED_BY_PURCHASING_APPROVER(21),
    SR_CREATE_ORACLE_PR_FAILED(22),
    SR_CREATE_ORACLE_PR_SUCCESSFULLY(23);

    private final Integer id;

    EmailActivity(Integer id) {
        this.id = id;
    }

    public Integer id() {
        return this.id;
    }
}
